### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by vkaragounis** [mit-wu-lab/IntersectionZoo#2]
I have noticed that "visualize.py" file is missing from the repository. Could you please provide access to this file cause it is essential to visualize the agents with 'sumo gui'?
 
Additionally, i would also like to ask for some clarifications about variable "visualize_sumo" since it is not recommended during training and that is indeed not necessary. However, in class "InterSectionZooEnvConfig" there is the following comment:  "whether to use SUMO's gui, doesn't always work very well with Ray" and I suspect that this may affect the use of 'sumo's gui' in testing mode (not training).

**Comment by Vindulamj** [comment]
Hi @vkaragounis, 

Thanks for bringing this to our attention. I am leaving a note here copying our email exchange on this, just in case it helps someone else later. 

We have fixed this issue, and you can now simply set `visualize=False` during training and set it back to `visualize=True` during evaluation to see the sumo GUI for visualization. Instructions can be found in the [documentation](https://intersectionzoo-docs.readthedocs.io/en/latest/usage.html#runnig-intersectionzoo). As you pointed out, we do not recommend having the visualization during training as it will slow down the training (we use multiple worker processes, each of which will load a sumo window with a different intersection environment). If you must use visualization during training, consider setting `num_workers `to a small number (ideally 1). There is no issue with using visualization during evaluation as given in policy_evaluation.py.

**Comment by Vindulamj** [comment]
I am closing this for now. But feel free to reopen it if you have any other questions.
